#!/usr/bin/env python3
"""Build the SOEP-Core v41 variable metadata from the OFFICIAL paneldata metadata.

Why this replaces the previous corpus: the live SOEP finder serves 22,097 variables whose
English text was generated by an LLM from a German label. The SOEP project publishes its own
structural metadata (github.com/paneldata/soep-core, the same source paneldata.org serves),
which gives, for v41:

  * 125,496 variables across 622 datasets, with a German AND an English label for ~100%
  * a concept per variable (76%) and a topic hierarchy over those concepts, so the finder
    finally has a real theme facet instead of one hardcoded string
  * the actual bilingual survey question wording for the concepts behind 36% of variables
  * response scales (answers.csv) reachable through those questions

Official beats generated: the labels are the ones SOEP itself uses, and a question text is the
wording respondents actually saw. LLM enrichment is a later pass for what remains bare, not the
foundation.

Inputs (downloaded from the paneldata repo):
  <finder>/new_data/paneldata_metadata/{variables,concepts,topics,datasets,questions,answers}.csv
Output:
  soep_metadata_output/soep_v41_metadata.json  (schema of _normalise_soep_row, plus the new
  bilingual/concept/topic fields it now reads)

Run:
  python scripts/build_soep_v41_metadata.py
  python scripts/build_soep_v41_metadata.py --limit 2000   # quick shape check
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
META_DIR = Path("/home/researcher/kwandel/soep-variable-finder/new_data/paneldata_metadata")
OUT_PATH = REPO_ROOT / "soep_metadata_output" / "soep_v41_metadata.json"
PANELDATA = "https://paneldata.org/soep-core/datasets"
MAX_QUESTIONS = 2
MAX_ANSWERS = 14


def clean(value: Any) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "none", "<na>"}:
        return ""
    return re.sub(r"\s+", " ", text)


def join_nonempty(parts: Iterable[str]) -> str:
    return "\n".join(part for part in parts if clean(part))


def topic_paths(topics: pd.DataFrame) -> Dict[str, Dict[str, str]]:
    """A topic's full path, so "Gesundheit und Pflege > Gesundheitszustand" is searchable as a
    whole rather than as a leaf."""
    by_name = {clean(r["name"]): r for _, r in topics.iterrows()}
    out: Dict[str, Dict[str, str]] = {}
    for name, row in by_name.items():
        chain_de: List[str] = []
        chain_en: List[str] = []
        current: Optional[Any] = row
        seen = set()
        while current is not None and clean(current["name"]) not in seen:
            seen.add(clean(current["name"]))
            chain_de.insert(0, clean(current.get("label_de")) or clean(current.get("label")))
            chain_en.insert(0, clean(current.get("label")) or clean(current.get("label_de")))
            parent = clean(current.get("parent"))
            current = by_name.get(parent) if parent else None
        out[name] = {"de": " > ".join(p for p in chain_de if p), "en": " > ".join(p for p in chain_en if p)}
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--out", default=str(OUT_PATH))
    parser.add_argument("--legacy", default=str(REPO_ROOT / "soep_metadata_output" / "soep_metadata_enriched.json"),
                        help="previous corpus, used only for value labels and distribution stats")
    args = parser.parse_args()

    variables = pd.read_csv(META_DIR / "variables.csv", low_memory=False)
    concepts = pd.read_csv(META_DIR / "concepts.csv", low_memory=False)
    topics = pd.read_csv(META_DIR / "topics.csv", low_memory=False)
    datasets = pd.read_csv(META_DIR / "datasets.csv", low_memory=False)
    questions = pd.read_csv(META_DIR / "questions.csv", low_memory=False)
    answers = pd.read_csv(META_DIR / "answers.csv", low_memory=False)

    paths = topic_paths(topics)
    concept_rows = {clean(r["name"]): r for _, r in concepts.iterrows()}
    dataset_rows = {clean(r["name"]): r for _, r in datasets.iterrows()}

    # Question wording per concept. variables.csv and logical_variables.csv use disjoint
    # dataset name spaces (checked: zero overlap), so the only usable bridge from a published
    # variable to a question is the shared `concept`.
    answer_lists: Dict[tuple, List[str]] = defaultdict(list)
    for _, row in answers.iterrows():
        key = (clean(row["instrument"]), clean(row["answer_list"]))
        label = clean(row.get("label_de")) or clean(row.get("label"))
        if label:
            answer_lists[key].append(f"{clean(row.get('value'))} = {label}")

    questions_by_concept: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    for _, row in questions.iterrows():
        concept = clean(row.get("concept"))
        text_de, text_en = clean(row.get("text_de")), clean(row.get("text"))
        if not concept or not (text_de or text_en):
            continue
        if len(questions_by_concept[concept]) >= MAX_QUESTIONS:
            continue
        scale = answer_lists.get((clean(row["instrument"]), clean(row.get("answer_list"))), [])
        questions_by_concept[concept].append({
            "de": text_de[:600], "en": text_en[:600],
            "scale": "; ".join(scale[:MAX_ANSWERS]),
        })

    # The official metadata has no value labels and no distribution statistics (categories in
    # variables.csv are empty), while the previous corpus extracted both from the .rds files.
    # 98% of the old rows exist in v41, so those two fields are carried over rather than lost.
    legacy: Dict[tuple, Dict[str, str]] = {}
    legacy_path = Path(args.legacy)
    if legacy_path.exists():
        for entry in json.loads(legacy_path.read_text(encoding="utf-8")):
            key = (clean(entry.get("dataset")), clean(entry.get("variable_name")))
            legacy[key] = {
                "value_labels": clean(entry.get("value_labels")),
                "stats_summary": clean(entry.get("stats_summary")),
                "sample_values": clean(entry.get("sample_values")),
            }
        print(f"[legacy] {len(legacy)} rows available for value labels and statistics")

    if args.limit:
        variables = variables.head(args.limit)

    records: List[Dict[str, Any]] = []
    for row in variables.itertuples(index=False):
        dataset = clean(getattr(row, "dataset", ""))
        name = clean(getattr(row, "name", ""))
        if not dataset or not name:
            continue
        label_de = clean(getattr(row, "label_de", "")) or clean(getattr(row, "label", ""))
        label_en = clean(getattr(row, "label", ""))
        concept = clean(getattr(row, "concept", ""))
        concept_row = concept_rows.get(concept)
        concept_de = clean(concept_row.get("label_de")) if concept_row is not None else ""
        concept_en = clean(concept_row.get("label")) if concept_row is not None else ""
        topic = clean(concept_row.get("topic")) if concept_row is not None else ""
        path = paths.get(topic, {})
        dataset_row = dataset_rows.get(dataset)
        dataset_de = clean(dataset_row.get("label_de")) if dataset_row is not None else ""
        dataset_en = clean(dataset_row.get("label")) if dataset_row is not None else ""
        analysis_unit = clean(dataset_row.get("analysis_unit")) if dataset_row is not None else ""
        conceptual = clean(dataset_row.get("conceptual_dataset")) if dataset_row is not None else ""
        period = clean(dataset_row.get("period")) if dataset_row is not None else ""
        folder = clean(dataset_row.get("folder")) if dataset_row is not None else ""
        asked = questions_by_concept.get(concept, [])

        carried = legacy.get((dataset, name), {})
        description_de = clean(getattr(row, "description_de", ""))
        description_en = clean(getattr(row, "description", ""))
        scale = next((q["scale"] for q in asked if q["scale"]), "") or carried.get("value_labels", "")

        rich = join_nonempty([
            f"{label_de} ({name}) im Datensatz {dataset_de or dataset} ({dataset}).",
            f"English label: {label_en}." if label_en and label_en != label_de else "",
            f"Konzept: {concept_de or concept}." if (concept_de or concept) else "",
            f"Themenbereich: {path.get('de', '')}." if path.get("de") else "",
            f"Offizielle Erläuterung: {description_de}" if description_de else "",
            f"Official note: {description_en}" if description_en else "",
            ("Fragetext: " + " | ".join(q["de"] for q in asked if q["de"])) if any(q["de"] for q in asked) else "",
            ("Question wording: " + " | ".join(q["en"] for q in asked if q["en"])) if any(q["en"] for q in asked) else "",
            f"Antwortkategorien: {scale}" if scale else "",
            f"Verteilung: {carried['stats_summary']}" if carried.get("stats_summary") else "",
            f"Erhebungseinheit: {analysis_unit}. Datensatzart: {conceptual}." if analysis_unit or conceptual else "",
        ])
        embedding_context = join_nonempty([
            f"Variable: {name}",
            f"Label (de): {label_de}",
            f"Label (en): {label_en}",
            f"Dataset: {dataset} ({dataset_de or dataset_en})",
            f"Concept: {concept_de} / {concept_en}" if (concept_de or concept_en) else "",
            f"Topic: {path.get('de', '')} / {path.get('en', '')}" if path else "",
            f"Question (de): {asked[0]['de']}" if asked and asked[0]["de"] else "",
            f"Question (en): {asked[0]['en']}" if asked and asked[0]["en"] else "",
            f"Answer categories: {scale}" if scale else "",
            f"Type: {clean(getattr(row, 'type', ''))}",
        ])

        records.append({
            "dataset": dataset,
            "variable_name": name,
            "label": label_de,
            "label_en": label_en,
            "value_labels": scale,
            "data_type": clean(getattr(row, "type", "")),
            "stats_summary": carried.get("stats_summary", ""),
            "sample_values": carried.get("sample_values", ""),
            "concept": concept,
            "concept_label": concept_de or concept_en,
            "topic": topic,
            "topic_path": path.get("de", ""),
            "topic_path_en": path.get("en", ""),
            "dataset_label_official": dataset_de or dataset_en,
            "analysis_unit": analysis_unit,
            "conceptual_dataset": conceptual,
            "period": period,
            "is_raw": folder.endswith("/raw"),
            "soep_version": clean(getattr(row, "version", "")) or "v41",
            "source_url": f"{PANELDATA}/{dataset}/{name}",
            "rich_description": rich,
            "embedding_context": embedding_context,
        })

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(records, ensure_ascii=False), encoding="utf-8")

    with_topic = sum(1 for r in records if r["topic_path"])
    with_question = sum(1 for r in records if "Fragetext:" in r["rich_description"])
    with_scale = sum(1 for r in records if r["value_labels"])
    with_stats = sum(1 for r in records if r["stats_summary"])
    print(json.dumps({
        "records": len(records),
        "datasets": len({r["dataset"] for r in records}),
        "with_english_label": sum(1 for r in records if r["label_en"]),
        "with_topic_path": with_topic,
        "with_question_text": with_question,
        "with_answer_scale": with_scale,
        "with_distribution_stats": with_stats,
        "raw_datasets": sum(1 for r in records if r["is_raw"]),
        "path": str(out),
        "size_mb": round(out.stat().st_size / 1e6, 1),
    }, indent=2))


if __name__ == "__main__":
    main()
