#!/usr/bin/env python3
"""Build the SOEP-Core v41 variable metadata from the OFFICIAL paneldata metadata.

Why this replaces the previous corpus: the live SOEP finder serves 22,097 variables whose
English text was generated by an LLM from a German label. The SOEP project publishes its own
structural metadata (github.com/paneldata/soep-core, the same source paneldata.org serves),
which gives, for v41:

  * 125,496 variables across 622 datasets, with a German AND an English label for ~100%
  * a concept per variable (76%) and a topic hierarchy over those concepts, so the finder
    finally has a real theme facet instead of one hardcoded string
  * the actual bilingual survey question wording for the concepts behind 36% of variables
  * response scales (answers.csv) reachable through those questions

Official beats generated: the labels are the ones SOEP itself uses, and a question text is the
wording respondents actually saw. LLM enrichment is a later pass for what remains bare, not the
foundation.

Inputs:
  <finder>/new_data/paneldata_metadata/{variables,concepts,topics,datasets,questions,answers}.csv
      downloaded from the paneldata repo (identical to its master on 2026-09-26)
  soep_metadata_output/soep_v41_rds_labels.tsv
      value labels and distributions read from the v41 .rds files, because the repo has none;
      written by scripts/extract_soep_v41_value_labels.R, which has to run first
  <finder>/new_data/publicecoredoku/datasets/<dataset>/v41/{SOEPhelp,generations,variable_categories}.csv
      the DIW's public SOEP-Core documentation (git clone https://git.soep.de/kwenzig/publicecoredoku.git,
      4.8 GB): the question each variable was asked with, the years, the English value labels
Output:
  soep_metadata_output/soep_v41_metadata.json  (schema of _normalise_soep_row, plus the new
  bilingual/concept/topic fields it now reads)

Run:
  OPENBLAS_NUM_THREADS=1 Rscript scripts/extract_soep_v41_value_labels.R   # about two minutes
  python scripts/build_soep_v41_metadata.py
  python scripts/build_soep_v41_metadata.py --limit 2000   # quick shape check
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
META_DIR = Path("/home/researcher/kwandel/soep-variable-finder/new_data/paneldata_metadata")
OUT_PATH = REPO_ROOT / "soep_metadata_output" / "soep_v41_metadata.json"
PANELDATA = "https://paneldata.org/soep-core/datasets"
MAX_QUESTIONS = 2
MAX_ANSWERS = 14
# Value labels read from the v41 .rds files (scripts/extract_soep_v41_value_labels.R). Occupation
# and region codes carry hundreds of categories; written out in full they fill the model's
# 512-token window before the question wording is reached, so the list is cut after this many.
RDS_LABELS = REPO_ROOT / "soep_metadata_output" / "soep_v41_rds_labels.tsv"
# The DIW's public SOEP-Core documentation in the soep-meta format (git.soep.de/kwenzig/publicecoredoku,
# pointed out by Knut Wenzig on 2026-09-30; the schema is described at git.soep.de/mds/soep-meta).
# The paneldata export above is generated from the same repository and agrees with it on labels
# and concepts, but it leaves out three things this builder now takes from here: the direct link
# from a variable to the question it was asked with (SOEPhelp.csv), the years it was asked in, and
# the English value labels (variable_categories.csv).
PUBLIC_DOKU = Path("/home/researcher/kwandel/soep-variable-finder/new_data/publicecoredoku")
DOKU_VERSION = "v41"
MAX_CATEGORIES = 20
MISSING_CODE = re.compile(r"^-\d+(?:\.\d+)?\s*:")


def clean(value: Any) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    if text.lower() in {"nan", "none", "<na>"}:
        return ""
    return re.sub(r"\s+", " ", text)


def join_nonempty(parts: Iterable[str]) -> str:
    return "\n".join(part for part in parts if clean(part))


def year_text(years: List[int]) -> str:
    """1984, 1985, ..., 2023 becomes "1984–2023"; gaps stay visible ("2016, 2018, 2020, 2022, 2023")."""
    if not years:
        return ""
    runs: List[List[int]] = [[years[0], years[0]]]
    for y in years[1:]:
        if y == runs[-1][1] + 1:
            runs[-1][1] = y
        else:
            runs.append([y, y])
    parts = [f"{a}–{b}" if b > a + 1 else (f"{a}, {b}" if b == a + 1 else str(a)) for a, b in runs]
    text = ", ".join(parts)
    if len(text) > 70:
        text = f"{years[0]}–{years[-1]} ({len(years)} Erhebungsjahre)"
    return text


def load_public_doku(dataset_names: Iterable[str], wave_year: Dict[str, int]) -> Dict[str, Dict[tuple, Any]]:
    """Direct questions, survey years and English value labels per (dataset, variable), for the
    datasets the paneldata export lists. Datasets the release does not contain are never read.

    Years come from the questions first (SOEPhelp.csv, the waves the item was asked in). A
    generated variable such as pgen/pglabnet was never asked; its generations.csv names the wave
    files it is built from (apgen, bpgen, ...), and those files' years are its years."""
    root = PUBLIC_DOKU / "datasets"
    questions: Dict[tuple, List[Dict[str, Any]]] = {}
    years: Dict[tuple, List[int]] = {}
    cats_en: Dict[tuple, str] = {}
    derived_years: Dict[tuple, set] = defaultdict(set)
    if not root.exists():
        print(f"[doku] {PUBLIC_DOKU} missing: git clone https://git.soep.de/kwenzig/publicecoredoku.git")
        return {"questions": questions, "years": years, "cats_en": cats_en}
    for ds in sorted(set(dataset_names)):
        folder = root / ds / DOKU_VERSION
        help_path = folder / "SOEPhelp.csv"
        if help_path.exists():
            h = pd.read_csv(help_path, dtype=str, keep_default_na=False, low_memory=False)
            h = h[h.get("study", "soep-core") == "soep-core"] if "study" in h else h
            h["y"] = pd.to_numeric(h["period"].where(h["period"].str.fullmatch(r"\d{4}")), errors="coerce")
            for var, g in h.groupby(h["variable"].str.lower()):
                key = (ds.lower(), var)
                ys = sorted({int(y) for y in g["y"].dropna()})
                if ys:
                    years[key] = ys
                seen, asked = set(), []
                for r in g.sort_values("y", ascending=False, na_position="last").itertuples(index=False):
                    de, en = clean(r.questiontext_de), clean(r.questiontext)
                    if not (de or en) or (de, en) in seen:
                        continue
                    seen.add((de, en))
                    asked.append({"de": de[:600], "en": en[:600], "scale": ""})
                    if len(asked) >= MAX_QUESTIONS:
                        break
                if asked:
                    questions[key] = asked
        gen_path = folder / "generations.csv"
        if gen_path.exists():
            g = pd.read_csv(gen_path, dtype=str, keep_default_na=False, low_memory=False)
            if {"output_dataset", "output_variable", "input_dataset"} <= set(g.columns):
                if "output_version" in g:
                    g = g[g["output_version"].isin([DOKU_VERSION, ""])]
                for od, ov, idd in zip(g["output_dataset"].str.lower(), g["output_variable"].str.lower(),
                                       g["input_dataset"].str.lower()):
                    if od == ds.lower() and idd in wave_year:
                        derived_years[(od, ov)].add(wave_year[idd])
        cat_path = folder / "variable_categories.csv"
        if cat_path.exists():
            c = pd.read_csv(cat_path, dtype=str, keep_default_na=False, low_memory=False)
            c = c[(c["label"] != "") & ~c["value"].str.startswith("-")]
            for var, g in c.groupby(c["variable"].str.lower()):
                cats_en[(ds.lower(), var)] = "; ".join(f"{v}: {l}" for v, l in zip(g["value"], g["label"]))
    year_source = {k: "questions" for k in years}
    for k, ys in derived_years.items():
        if k not in years and ys:
            years[k] = sorted(ys)
            year_source[k] = "generations"
    print(f"[doku] {len(questions)} variables with a directly linked question, {len(years)} with survey "
          f"years ({sum(1 for v in year_source.values() if v == 'generations')} of them from generations.csv), "
          f"{len(cats_en)} with English value labels")
    return {"questions": questions, "years": years, "year_source": year_source, "cats_en": cats_en}


def substantive_categories(scale: str) -> str:
    """The answer categories without SOEP's standard missing codes (-1 to -9: no answer, does not
    apply, not asked this year, ...). Those nine are the same on nearly every variable, about 400
    characters, so leaving them in makes tens of thousands of documents alike in exactly the part
    that should tell them apart. The service strips them too, but only from lines it recognises,
    and the "Answer categories:" line this script writes was not one of them until 2026-09-26."""
    parts = [p.strip() for p in (scale or "").split(";") if p.strip() and not MISSING_CODE.match(p.strip())]
    if len(parts) > MAX_CATEGORIES:
        parts = parts[:MAX_CATEGORIES] + [f"… (+{len(parts) - MAX_CATEGORIES} weitere)"]
    return "; ".join(parts)


def topic_paths(topics: pd.DataFrame) -> Dict[str, Dict[str, str]]:
    """A topic's full path, so "Gesundheit und Pflege > Gesundheitszustand" is searchable as a
    whole rather than as a leaf."""
    by_name = {clean(r["name"]): r for _, r in topics.iterrows()}
    out: Dict[str, Dict[str, str]] = {}
    for name, row in by_name.items():
        chain_de: List[str] = []
        chain_en: List[str] = []
        current: Optional[Any] = row
        seen = set()
        while current is not None and clean(current["name"]) not in seen:
            seen.add(clean(current["name"]))
            chain_de.insert(0, clean(current.get("label_de")) or clean(current.get("label")))
            chain_en.insert(0, clean(current.get("label")) or clean(current.get("label_de")))
            parent = clean(current.get("parent"))
            current = by_name.get(parent) if parent else None
        out[name] = {"de": " > ".join(p for p in chain_de if p), "en": " > ".join(p for p in chain_en if p)}
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--out", default=str(OUT_PATH))
    # Switches for measuring what each addition from the DIW documentation does to retrieval.
    parser.add_argument("--question-mode", choices=["display", "embed-direct", "concept"], default="display",
                        help="display (default): the question linked in SOEPhelp.csv is shown to the reader, "
                             "the embedded text keeps the concept's question; embed-direct: the linked question "
                             "also goes into the embedded text; concept: only the concept route, as before 2026-09-30")
    parser.add_argument("--no-english-categories", action="store_true",
                        help="leave the English value labels out of the embedded text")
    parser.add_argument("--legacy", default=str(REPO_ROOT / "soep_metadata_output" / "soep_metadata_enriched.json"),
                        help="previous corpus, used only for value labels and distribution stats")
    args = parser.parse_args()

    variables = pd.read_csv(META_DIR / "variables.csv", low_memory=False)
    concepts = pd.read_csv(META_DIR / "concepts.csv", low_memory=False)
    topics = pd.read_csv(META_DIR / "topics.csv", low_memory=False)
    datasets = pd.read_csv(META_DIR / "datasets.csv", low_memory=False)
    questions = pd.read_csv(META_DIR / "questions.csv", low_memory=False)
    answers = pd.read_csv(META_DIR / "answers.csv", low_memory=False)

    paths = topic_paths(topics)
    concept_rows = {clean(r["name"]): r for _, r in concepts.iterrows()}
    dataset_rows = {clean(r["name"]): r for _, r in datasets.iterrows()}

    wave_year = {clean(r["name"]).lower(): int(clean(r["period"])) for _, r in datasets.iterrows()
                 if clean(r["period"]).isdigit() and len(clean(r["period"])) == 4}
    doku = load_public_doku(variables["dataset"].dropna().astype(str).str.lower(), wave_year)

    # Question wording per concept, the fallback where the documentation links no question
    # directly. variables.csv and logical_variables.csv of the paneldata export use disjoint
    # dataset name spaces, so there the only bridge from a variable to a question is the concept,
    # which may lead to the same concept asked in another questionnaire.
    answer_lists: Dict[tuple, List[str]] = defaultdict(list)
    for _, row in answers.iterrows():
        key = (clean(row["instrument"]), clean(row["answer_list"]))
        label = clean(row.get("label_de")) or clean(row.get("label"))
        if label:
            answer_lists[key].append(f"{clean(row.get('value'))} = {label}")

    questions_by_concept: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    for _, row in questions.iterrows():
        concept = clean(row.get("concept"))
        text_de, text_en = clean(row.get("text_de")), clean(row.get("text"))
        if not concept or not (text_de or text_en):
            continue
        if len(questions_by_concept[concept]) >= MAX_QUESTIONS:
            continue
        scale = answer_lists.get((clean(row["instrument"]), clean(row.get("answer_list"))), [])
        questions_by_concept[concept].append({
            "de": text_de[:600], "en": text_en[:600],
            "scale": "; ".join(scale[:MAX_ANSWERS]),
        })

    # The official metadata has no value labels and no distribution statistics (categories in
    # variables.csv are empty, at the v40.0 tag as well). Both come from the v41 .rds files now,
    # for every labelled variable. The previous corpus (v40, 22,097 variables) is only the
    # fallback for the seven restricted datasets that have no file here.
    rds: Dict[tuple, Dict[str, str]] = {}
    if RDS_LABELS.exists():
        table = pd.read_csv(RDS_LABELS, sep="\t", dtype=str, keep_default_na=False, quoting=3)
        for r in table.itertuples(index=False):
            rds[(r.dataset, r.variable)] = {"value_labels": r.value_labels, "stats_summary": r.stats,
                                            "years": [int(y) for y in getattr(r, "years", "").split(",") if y]}
        print(f"[rds] {len(rds)} variables with labels and statistics from the v41 data files")
    else:
        print(f"[rds] {RDS_LABELS} missing: run scripts/extract_soep_v41_value_labels.R first")
    legacy: Dict[tuple, Dict[str, str]] = {}
    legacy_path = Path(args.legacy)
    if legacy_path.exists():
        for entry in json.loads(legacy_path.read_text(encoding="utf-8")):
            key = (clean(entry.get("dataset")), clean(entry.get("variable_name")))
            legacy[key] = {
                "value_labels": clean(entry.get("value_labels")),
                "stats_summary": clean(entry.get("stats_summary")),
                "sample_values": clean(entry.get("sample_values")),
            }
        print(f"[legacy] {len(legacy)} rows available for value labels and statistics")

    if args.limit:
        variables = variables.head(args.limit)

    # Machine translations of the missing half of a label pair (scripts/translate_soep_labels.py).
    # They never replace an official label: they are extra search text, marked as MT wherever
    # they surface, because the official label is the authoritative wording.
    translations: Dict[str, Dict[str, str]] = {}
    translations_path = OUT_PATH.parent / "soep_label_translations.json"
    if translations_path.exists():
        translations = json.loads(translations_path.read_text(encoding="utf-8")).get("translations") or {}
        print(f"[translations] {len(translations)} machine-translated labels available")

    records: List[Dict[str, Any]] = []
    for row in variables.itertuples(index=False):
        dataset = clean(getattr(row, "dataset", ""))
        name = clean(getattr(row, "name", ""))
        if not dataset or not name:
            continue
        label_de = clean(getattr(row, "label_de", "")) or clean(getattr(row, "label", ""))
        label_en = clean(getattr(row, "label", ""))
        concept = clean(getattr(row, "concept", ""))
        concept_row = concept_rows.get(concept)
        concept_de = clean(concept_row.get("label_de")) if concept_row is not None else ""
        concept_en = clean(concept_row.get("label")) if concept_row is not None else ""
        topic = clean(concept_row.get("topic")) if concept_row is not None else ""
        path = paths.get(topic, {})
        dataset_row = dataset_rows.get(dataset)
        dataset_de = clean(dataset_row.get("label_de")) if dataset_row is not None else ""
        dataset_en = clean(dataset_row.get("label")) if dataset_row is not None else ""
        analysis_unit = clean(dataset_row.get("analysis_unit")) if dataset_row is not None else ""
        conceptual = clean(dataset_row.get("conceptual_dataset")) if dataset_row is not None else ""
        period = clean(dataset_row.get("period")) if dataset_row is not None else ""
        folder = clean(dataset_row.get("folder")) if dataset_row is not None else ""
        # Shown and embedded are kept apart on purpose. Measured on 2026-09-30 with the 59-query
        # SOEP gate: putting the directly linked question into the embedded text of 27,000 more
        # questionnaire items pushed generated variables (pgbilzeit, pgstib, pgemplst) out of the
        # candidate pool, three misses instead of none (MRR 0.891 -> 0.860). Years and English
        # categories alone were neutral to slightly better (0.898). So the reader sees the question
        # the variable was really asked with, and retrieval keeps the text it was tuned on.
        direct = doku["questions"].get((dataset.lower(), name.lower())) if args.question_mode != "concept" else None
        by_concept = questions_by_concept.get(concept, [])
        asked = direct or by_concept                                  # shown to the reader
        embedded = asked if args.question_mode == "embed-direct" else by_concept
        question_source = ("direct" if direct else "concept") if asked else ""
        own = rds.get((dataset.lower(), name.lower()), {})
        # Years in order of certainty: the data itself (a long file's syear with a valid value),
        # then the waves the question was asked in, then the waves a generated variable is built
        # from, then a raw wave file's own year.
        years, years_source = own.get("years") or [], "data"
        if not years:
            years = doku["years"].get((dataset.lower(), name.lower()), [])
            years_source = doku["year_source"].get((dataset.lower(), name.lower()), "") if years else ""
        if not years and period.isdigit() and len(period) == 4:
            years, years_source = [int(period)], "dataset"   # a raw wave file describes one year
        categories_en = "" if args.no_english_categories else substantive_categories(
            doku["cats_en"].get((dataset.lower(), name.lower()), ""))

        carried = legacy.get((dataset, name), {})
        description_de = clean(getattr(row, "description_de", ""))
        description_en = clean(getattr(row, "description", ""))
        # The variable's own labels first: a question reached through the concept may come from
        # another questionnaire with another scale. v40 only where no v41 file exists.
        # A directly linked question carries no answer list here, so the scale of the concept's
        # question stays the fallback it was before the direct links existed.
        question_scale = next((q["scale"] for q in list(asked) + questions_by_concept.get(concept, [])
                               if q.get("scale")), "")
        candidates = [("rds", own.get("value_labels", "")), ("question", question_scale),
                      ("v40", carried.get("value_labels", ""))]
        scale_source, scale = next(((src, substantive_categories(s)) for src, s in candidates
                                    if substantive_categories(s)), ("", ""))
        stats_summary = own.get("stats_summary") or ("" if own else carried.get("stats_summary", ""))

        translated = translations.get(f"{dataset}/{name}", {})
        label_de_mt = clean(translated.get("label_de_mt"))
        label_en_mt = clean(translated.get("label_en_mt"))

        rich = join_nonempty([
            f"{label_de} ({name}) im Datensatz {dataset_de or dataset} ({dataset}).",
            f"English label: {label_en}." if label_en and label_en != label_de else "",
            f"Deutsche Übersetzung (maschinell): {label_de_mt}." if label_de_mt else "",
            f"English translation (machine): {label_en_mt}." if label_en_mt else "",
            f"Konzept: {concept_de or concept}." if (concept_de or concept) else "",
            f"Themenbereich: {path.get('de', '')}." if path.get("de") else "",
            f"Offizielle Erläuterung: {description_de}" if description_de else "",
            f"Official note: {description_en}" if description_en else "",
            ("Fragetext: " + " | ".join(q["de"] for q in asked if q["de"])) if any(q["de"] for q in asked) else "",
            ("Question wording: " + " | ".join(q["en"] for q in asked if q["en"])) if any(q["en"] for q in asked) else "",
            f"Antwortkategorien: {scale}" if scale else "",
            f"Verteilung: {stats_summary}" if stats_summary else "",
            f"Erhebungseinheit: {analysis_unit}. Datensatzart: {conceptual}." if analysis_unit or conceptual else "",
        ])
        embedding_context = join_nonempty([
            f"Variable: {name}",
            f"Label (de): {label_de}",
            f"Label (en): {label_en}",
            # The translated side only exists where SOEP publishes the label in one language,
            # which is the whole point: without it "Familienstand" cannot match pgfamstd, whose
            # German label reads "Marital Status".
            f"Label (de, machine translation): {label_de_mt}" if label_de_mt else "",
            f"Label (en, machine translation): {label_en_mt}" if label_en_mt else "",
            f"Dataset: {dataset} ({dataset_de or dataset_en})",
            f"Concept: {concept_de} / {concept_en}" if (concept_de or concept_en) else "",
            f"Topic: {path.get('de', '')} / {path.get('en', '')}" if path else "",
            f"Question (de): {embedded[0]['de']}" if embedded and embedded[0]["de"] else "",
            f"Question (en): {embedded[0]['en']}" if embedded and embedded[0]["en"] else "",
            f"Answer categories: {scale}" if scale else "",
            f"Answer categories (en): {categories_en}" if categories_en else "",
            f"Type: {clean(getattr(row, 'type', ''))}",
        ])

        records.append({
            "dataset": dataset,
            "variable_name": name,
            "label": label_de,
            "label_en": label_en,
            "label_de_mt": label_de_mt,
            "label_en_mt": label_en_mt,
            "value_labels": scale,
            "value_labels_source": scale_source,
            "value_labels_en": categories_en,
            "question_source": question_source,
            "survey_years": years,
            "survey_years_source": years_source,
            "year_start": years[0] if years else None,
            "year_end": years[-1] if years else None,
            "available_years_text": year_text(years),
            "data_type": clean(getattr(row, "type", "")),
            "stats_summary": stats_summary,
            "sample_values": carried.get("sample_values", ""),
            "concept": concept,
            "concept_label": concept_de or concept_en,
            "topic": topic,
            "topic_path": path.get("de", ""),
            "topic_path_en": path.get("en", ""),
            "dataset_label_official": dataset_de or dataset_en,
            "analysis_unit": analysis_unit,
            "conceptual_dataset": conceptual,
            "period": period,
            "is_raw": folder.endswith("/raw"),
            "soep_version": clean(getattr(row, "version", "")) or "v41",
            "source_url": f"{PANELDATA}/{dataset}/{name}",
            "rich_description": rich,
            "embedding_context": embedding_context,
        })

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(records, ensure_ascii=False), encoding="utf-8")

    with_topic = sum(1 for r in records if r["topic_path"])
    with_question = sum(1 for r in records if "Fragetext:" in r["rich_description"])
    question_from = {src: sum(1 for r in records if r["question_source"] == src) for src in ("direct", "concept")}
    with_years = {src: sum(1 for r in records if r["survey_years_source"] == src)
                  for src in ("data", "questions", "generations", "dataset")}
    with_scale = sum(1 for r in records if r["value_labels"])
    with_stats = sum(1 for r in records if r["stats_summary"])
    scale_sources = {src: sum(1 for r in records if r["value_labels_source"] == src) for src in ("rds", "question", "v40")}
    print(json.dumps({
        "records": len(records),
        "datasets": len({r["dataset"] for r in records}),
        "with_english_label": sum(1 for r in records if r["label_en"]),
        "with_topic_path": with_topic,
        "with_question_text": with_question,
        "question_from": question_from,
        "with_survey_years": with_years,
        "with_english_value_labels": sum(1 for r in records if r["value_labels_en"]),
        "with_answer_scale": with_scale,
        "with_distribution_stats": with_stats,
        "answer_scale_from": scale_sources,
        "raw_datasets": sum(1 for r in records if r["is_raw"]),
        "path": str(out),
        "size_mb": round(out.stat().st_size / 1e6, 1),
    }, indent=2))


if __name__ == "__main__":
    main()
